# Generated by Django 4.2.9 on 2024-01-18 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("userName", models.CharField(default="", max_length=50)),
                ("userEmail", models.EmailField(default="", max_length=50)),
                ("password", models.CharField(default="", max_length=50)),
            ],
        ),
    ]
